# Introduccion Diccionarios

Tal vez conozcas el tipo de dato **listas**, las listas son utiles pero presentan pasos un poco detallados para acceder a la informacion, veamos el siguiente ejemplo:

Para ver por qué los diccionarios son útiles, echa un vistazo a las dos listas definidas. **countries** contiene los nombres de algunos países europeos. **capitals** enumera los nombres correspondientes a sus capitales.

In [1]:
# Definición de países y capitales
countries = ['spain', 'france', 'germany', 'norway']
capitals = ['madrid', 'paris', 'berlin', 'oslo']

# Obtén el índice de 'germany': ind_ger
ind_ger = countries.index('germany')

# Usa ind_ger para imprimir la capital de Alemania
print(capitals[ind_ger])

berlin

# Diccionarios

Ahora convertiremos estos datos en un diccionario en el que los nombres de los países sean las claves y las capitales los valores correspondientes. Como repaso, aquí hay una receta para crear un diccionario:

```
my_dict = {
"key1":"value1",
"key2":"value2",
}
```

In [2]:
# Definición de países y capitales
countries = ['spain', 'france', 'germany', 'norway']
capitals = ['madrid', 'paris', 'berlin', 'oslo']

# A partir de un string en countries y capitals, crea un diccionario europe
europe = {'spain':'madrid', 'france': 'paris', 'germany':'berlin', 'norway':'oslo' }

# Imprime europe
print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo'}

## Acceder al diccionario

Si las claves (keys) de un diccionario se eligen con inteligencia, acceder a los valores del diccionario es fácil e intuitivo. Por ejemplo, para obtener la capital de Francia utilizando europe, puedes usar:

```europe['france']```

In [3]:
# Definición de diccionario
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# Imprime las llaves en europe
print(europe.keys())

# Imprime el valor que pertenece a la clave 'norway'
print(europe['norway'])

dict_keys(['spain', 'france', 'germany', 'norway'])
oslo

## Manipulacion de diccionarios

Si sabes cómo acceder a un diccionario, también puedes asignarle un nuevo valor. Para añadir un nuevo par clave-valor a **europe**, puedes usar algo como esto:

```europe['iceland'] = 'reykjavik'```

In [4]:
# Definición de diccionario
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# Añade italy a europe
europe['italy'] = 'rome'

# Imprime italy en europe
print('italy' in europe) #Si se encuentra (True) si no (False)

# Añade poland a europe
europe['poland'] = 'warsaw'

# Imprime europe
print(europe)

True
{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

## Eliminar elemento

In [5]:
# Definición de diccionario
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# Cambia la capital de Alemania
europe['germany'] = 'berlin'

# Elimina australia
del(europe['australia'])

# Imprime europe
print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

## Diccionario de diccionarios

¿Recuerdas las listas? Pueden contener cualquier cosa, incluso otras listas. Bueno, para los diccionarios ocurre lo mismo. Los diccionarios pueden contener pares clave:valor en los que los valores vuelven a ser diccionarios.

Como ejemplo, echa un vistazo al código en el que está codificada otra versión de **europe**, el diccionario con el que has estado trabajando todo el tiempo. Las claves siguen siendo los nombres de los países, pero los valores son diccionarios que contienen más información que solo la capital.

Es perfectamente posible encadenar corchetes para seleccionar elementos. Para obtener la población de España de **europe**, por ejemplo, tú necesitas:

```europe['spain']['population']```

In [9]:
# Diccionario de diccionarios
europe = { 'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } }


# Imprime la capital de Francia
europe['france']['capital']

# Crea los datos del sub-diccionario
data = {'capital':'rome','population': 59.83}

# Añada datos a Europa con la clave 'italy'
europe['italy'] = data

# Imprime europe
print(europe)

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'italy': {'capital': 'rome', 'population': 59.83}}

**Esta es una breve introduccion a diccionarios,puedes abordar mas en el tema en: [Diccionarios](../Notebooks/Diccionarios.ipynb)**

# Pandas

Pandas es una biblioteca de código abierto que proporciona estructuras de datos y herramientas de análisis de datos de alto rendimiento y fáciles de usar para Python. 

El DataFrame es una de las estructuras de datos más importantes de Pandas. Básicamente es una forma de almacenar datos tabulares donde puedes etiquetar las filas y las columnas. 

Una forma de crear un DataFrame es desde un diccionario.

En los ejercicios siguientes trabajarás con datos de vehículos de diferentes países. Cada observación corresponde a un país y las columnas proporcionan información sobre el número de vehículos per cápita, si las personas conducen a la izquierda o a la derecha, etc.

## Diccionario a DataFrame

Se definen tres listas en el script:

- **names:** contiene los nombres de los países para los que hay datos disponibles.

- **dr:** lista con valores booleanos que indica si las personas conducen a la izquierda o a la derecha en el país correspondiente.

- **cpc:** número de vehículos de motor por cada 1000 personas en el país correspondiente.

Cada clave del diccionario es una etiqueta de columna y cada valor es una lista que contiene los elementos de la columna.

In [10]:
# Instalar biblioteca pandas
%pip install pandas

Requirement already satisfied: pandas in c:\users\jorgehdz\appdata\local\programs\python\python39\lib\site-packages (2.1.3)
Requirement already satisfied: numpy<2,>=1.22.4 in c:\users\jorgehdz\appdata\local\programs\python\python39\lib\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jorgehdz\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\jorgehdz\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\jorgehdz\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\jorgehdz\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
# Listas predefinidas
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

# Import pandas as pd
import pandas as pd

# Crea el diccionario my_dict con tres pares clave:valor: my_dict
my_dict = {'country':names,'drives_right':dr,'cars_per_cap':cpc}

# Construye un DataFrame cars a partir de my_dict: cars
cars = pd.DataFrame(my_dict)

# Imprime cars
cars

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

## Cambiar indice

El código Python que resuelve el ejercicio anterior se incluye en el código. ¿Has notado que las etiquetas de las filas (es decir, las etiquetas de las diferentes observaciones) se establecieron automáticamente en números enteros del 0 al 6?

Para solucionar esto, se ha creado una lista **row_labels** . Puedes usarla para especificar las etiquetas de las filas del DataFrame de **cars**. Para ello, configura el atributo **index** de **cars**, al que puedes acceder como **cars.index**.

In [12]:
import pandas as pd

# Construye un DataFrame cars
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
cars_dict = { 'country':names, 'drives_right':dr, 'cars_per_cap':cpc }
cars = pd.DataFrame(cars_dict)
print(cars)

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [13]:
# Definición de row_labels
row_labels = ['US', 'AUS', 'JPN', 'IN', 'RU', 'MOR', 'EG']

# Especifica las etiquetas de las filas de los coches
cars.index = row_labels

# Vuelve a imprimir cars
print(cars)

           country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JPN          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

## CSV a DataFrame

Poner datos en un diccionario y luego crear un DataFrame funciona, pero no es muy eficiente. ¿Qué pasa si se trata de millones de observaciones? En esos casos, los datos suelen estar disponibles como archivos con una estructura regular. Uno de esos tipos de archivos es el archivo CSV, que es la abreviatura de «valores separados por comas» en inglés.

Para importar datos CSV a Python como un Pandas DataFrame, puedes usar ```read_csv()```.

Vamos a explorar esta función con los mismos datos de los coches de los ejercicios anteriores. Esta vez, sin embargo, los datos están disponibles en un archivo CSV denominado cars.csv. Está disponible con el nombre de ```'cars.csv'```.

In [16]:
# Importa pandas as pd
import pandas as pd

# Importa el archivo cars.csv data: cars
cars = pd.read_csv('cars.csv')

# Imprime coches
print(cars)

  Unnamed: 0  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JPN           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True

Tu llamada a ```read_csv()``` para importar los datos del CSV no generó ningún error, pero el resultado no es del todo lo que queríamos. Las etiquetas de fila se importaron como otra columna sin nombre.

¿Recuerdas ```index_col```, un argumento de ```read_csv()```, que puedes usar para especificar qué columna del archivo CSV debe usarse como etiqueta de fila? Bueno, ¡eso es exactamente lo que necesitas aquí!

In [17]:
# Importa pandas as pd
import pandas as pd

# Corrige la importación incluyendo index_col
cars = pd.read_csv('cars.csv',index_col = 0)

# Imprime coches
print(cars)

            cars_per_cap        country  drives_right
Unnamed: 0
US                   809  United States          True
AUS                  731      Australia         False
JPN                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

## Corchetes

En Pandas, se puede indexar y seleccionar Pandas DataFrames de muchas formas diferentes.

La forma más simple, pero no la más poderosa, es usar corchetes.

En el código de ejemplo, se importan los mismos datos de **cars** desde un archivo CSV como un Pandas DataFrame. Para seleccionar solo la columna ```cars_per_cap``` de **cars**, puedes usar:

```
cars['cars_per_cap']
cars[['cars_per_cap']]
```

La versión de un solo corchete ofrece una serie Pandas, la versión de doble corchete proporciona un Pandas DataFrame.

In [23]:
# Importa datos de cars
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Imprime la columna country como Pandas Series
print("Series country")
print(cars['country'])

# Imprime la columna country como Pandas DataFrame
print("\nDataFrame country")
print(cars[['country']])

# Imprime DataFrame con las columnas country y drives_right
print("\nDataFrame country y drives_right")
print(cars[['country', 'drives_right']])

Series country
Unnamed: 0
US     United States
AUS        Australia
JPN            Japan
IN             India
RU            Russia
MOR          Morocco
EG             Egypt
Name: country, dtype: object

DataFrame country
                  country
Unnamed: 0
US          United States
AUS             Australia
JPN                 Japan
IN                  India
RU                 Russia
MOR               Morocco
EG                  Egypt

DataFrame country y drives_right
                  country  drives_right
Unnamed: 0
US          United States          True
AUS             Australia         False
JPN                 Japan         False
IN                  India         False
RU                 Russia          True
MOR               Morocco          True
EG                  Egypt          True

Los corchetes permiten mucho más que seleccionar columnas. También puedes usarlos para obtener filas u observaciones de un DataFrame. La siguiente llamada selecciona las cinco primeras filas del DataFrame cars:

```cars[0:5]```

El resultado es otro DataFrame que contiene solo las filas que especificaste.

**Nota: Solo puedes seleccionar filas con corchetes si especificas un sector, por ejemplo 0:4.** 

Además, aquí está utilizando los índices enteros de las filas, las etiquetas no se utilizan

In [26]:
# Importa datos de cars
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Imprime las 3 primeras observaciones
print("Primeras 3 filas u observaciones")
print(cars[0:3])

# Imprime la cuarta, quinta y sexta observación
print("\nCuarta, quinta y sexta observación")
print(cars[3:6])

Primeras 3 filas u observaciones
            cars_per_cap        country  drives_right
Unnamed: 0
US                   809  United States          True
AUS                  731      Australia         False
JPN                  588          Japan         False

Cuarta, quinta y sexta observación
            cars_per_cap  country  drives_right
Unnamed: 0
IN                    18    India         False
RU                   200   Russia          True
MOR                   70  Morocco          True

## Loc y iloc

Con ```loc``` y ```iloc``` puedes realizar prácticamente cualquier operación de selección de datos en DataFrames que se te ocurra. `

```loc``` se basa en etiquetas, lo que significa que debes especificar filas y columnas en función de sus etiquetas de fila y columna. 

```iloc``` se basa en índices de enteros, por lo que debes especificar las filas y columnas por su índice de enteros, como en el ejercicio anterior.

In [28]:
# Importa datos de cars
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

cars

            cars_per_cap        country  drives_right
Unnamed: 0
US                   809  United States          True
AUS                  731      Australia         False
JPN                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

### Datos con Loc

In [30]:
# Imprime la observación de Japón
print("Serie de la observacion de Japon")
print(cars.loc['JPN'])


# Imprime las observaciones de Australia y Egipto
print("\nDataFrame observaciones")
print(cars.loc[['AUS','EG']])

Serie de la observacion de Japon
cars_per_cap      588
country         Japan
drives_right    False
Name: JPN, dtype: object

DataFrame observaciones
            cars_per_cap    country  drives_right
Unnamed: 0
AUS                  731  Australia         False
EG                    45      Egypt          True

### Datos con iloc

In [35]:
# Imprime la observación de Japón
print("Serie de la observacion de Japon")
print(cars.iloc[2])


# Imprime las observaciones de Australia y Egipto
print("\nDataFrame observaciones")
print(cars.iloc[[1,-1]]) #-1 accede al ultimo elemento

Serie de la observacion de Japon
cars_per_cap      588
country         Japan
drives_right    False
Name: JPN, dtype: object

DataFrame observaciones
            cars_per_cap    country  drives_right
Unnamed: 0
AUS                  731  Australia         False
EG                    45      Egypt          True

## Filas y Columnas con loc y iloc

```loc``` y ```iloc``` también te permiten seleccionar filas y columnas de un DataFrame. 

Algunos ejemplos de esto son:

```
cars.loc['IN', 'cars_per_cap']
cars.iloc[3, 0]

cars.loc[['IN', 'RU'], 'cars_per_cap']
cars.iloc[[3, 4], 0]

cars.loc[['IN', 'RU'], ['cars_per_cap', 'country']]
cars.iloc[[3, 4], [0, 1]]
```

### Filas y Columnas con loc

In [37]:
# Importa datos de cars
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Imprime el valor drives_right de Marruecos
print("Valor de Marruecos en la columna manejo derecho")
print(cars.loc[['MOR'],'drives_right'])

# Imprime el sub-DataFrame
print("\nSub-DataFrame de RUSIA Y MARRUECOS en las columnas pais y manejo derecho")
print(cars.loc[['RU','MOR'],['country','drives_right']])

Valor de Marruecos en la columna manejo derecho
Unnamed: 0
MOR    True
Name: drives_right, dtype: bool

Sub-DataFrame de RUSIA Y MARRUECOS en las columnas pais y manejo derecho
            country  drives_right
Unnamed: 0
RU           Russia          True
MOR         Morocco          True

### Filas y columnas con iloc

In [40]:
# Importa datos de cars
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Imprime el valor drives_right de Marruecos
print("Valor de Marruecos en la columna manejo derecho")
print(cars.iloc[[5],2])

# Imprime el sub-DataFrame
print("\nSub-DataFrame de RUSIA Y MARRUECOS en las columnas pais y manejo derecho")
print(cars.iloc[[4,5],[1,2]])

Valor de Marruecos en la columna manejo derecho
Unnamed: 0
MOR    True
Name: drives_right, dtype: bool

Sub-DataFrame de RUSIA Y MARRUECOS en las columnas pais y manejo derecho
            country  drives_right
Unnamed: 0
RU           Russia          True
MOR         Morocco          True

## Columnas con loc y iloc

También es posible seleccionar solo las columnas con ```loc``` y ```iloc```. 

En ambos casos, basta con poner una fracción que vaya de principio a fin delante de la coma:

```
cars.loc[:, 'country']
cars.iloc[:, 1]

cars.loc[:, ['country','drives_right']]
cars.iloc[:, [1, 2]]
```

In [41]:
# Importa datos de cars
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Imprime la columna drives_right como Serie
print("Drives_right como serie")
print(cars.loc[:,'drives_right'])

# Imprime la columna drives_right como DataFrame
print("\nDrives_right como DataFrame")
print(cars.loc[:,['drives_right']])

# Imprime cars_per_cap y drives_right como DataFrame
print("\nCars_per_cap y drives_right como DataFrame")
print(cars.loc[:,['cars_per_cap','drives_right']])

Drives_right como serie
Unnamed: 0
US      True
AUS    False
JPN    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool

Drives_right como DataFrame
            drives_right
Unnamed: 0
US                  True
AUS                False
JPN                False
IN                 False
RU                  True
MOR                 True
EG                  True

Cars_per_cap y drives_right como DataFrame
            cars_per_cap  drives_right
Unnamed: 0
US                   809          True
AUS                  731         False
JPN                  588         False
IN                    18         False
RU                   200          True
MOR                   70          True
EG                    45          True